repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-check
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.411
    hooks:
    - id: pyright
  - repo: local
    hooks:
      - id: sphinx-apidoc
        name: sphinx-apidoc (regenerate API doc module stubs)
        entry: sphinx-apidoc -f -o docs/source bedroc
        language: python
        additional_dependencies: ["sphinx>=8.2.3"]
        pass_filenames: false
        files: ^bedroc/.*\.py$